export enum SeatType {
  GOLD = 'GOLD',
  SILVER = 'SILVER',
  PLATINUM = 'PLATINUM',
  STANDARD = 'STANDARD',
}

export enum BookingStatus {
  PENDING = 'PENDING',
  CONFIRMED = 'CONFIRMED',
  CANCELLED = 'CANCELLED',
  REFUNDED = 'REFUNDED',
}

export enum AuditAction {
  CREATE = 'CREATE',
  UPDATE = 'UPDATE',
  DELETE = 'DELETE',
  LOGIN = 'LOGIN',
  LOGOUT = 'LOGOUT',
  BOOKING_CREATED = 'BOOKING_CREATED',
  BOOKING_UPDATED = 'BOOKING_UPDATED',
  BOOKING_CANCELLED = 'BOOKING_CANCELLED',
  PAYMENT_PROCESSED = 'PAYMENT_PROCESSED',
  PAYMENT_REFUNDED = 'PAYMENT_REFUNDED',
  USER_CREATED = 'USER_CREATED',
  USER_UPDATED = 'USER_UPDATED',
  USER_DELETED = 'USER_DELETED',
  ROLE_ASSIGNED = 'ROLE_ASSIGNED',
  PERMISSION_GRANTED = 'PERMISSION_GRANTED',
}

export enum AuditEntityType {
  USER = 'USER',
  BOOKING = 'BOOKING',
  PAYMENT = 'PAYMENT',
  MOVIE = 'MOVIE',
  SHOW = 'SHOW',
  THEATER = 'THEATER',
  ROLE = 'ROLE',
  PERMISSION = 'PERMISSION',
  CONCESSION = 'CONCESSION',
  CONCESSION_CATEGORY = 'CONCESSION_CATEGORY',
  CONCESSION_ORDER = 'CONCESSION_ORDER',
}